### ISSUE TITLE
Disabled and readonly state attributes and label styles are missing

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-custom-field#30]
The label in other Vaadin fields reflect the field status, e.g. is highlighted when the field is focused and grayed-out when the field is disabled; also, clicking on the custom-field label doesn't focus the wrapped field.

<img width="681" alt="Screenshot 2019-05-23 at 09 11 34" src="https://user-images.githubusercontent.com/851745/58232822-d06eac80-7d3a-11e9-94a5-b003c430d944.png">

Glitch: https://band-pony.glitch.me/

**Comment by heruan** [comment]
I understand the custom-field could not be aware of its content, but I would expect a property to bind/propagate the field status.

**Comment by web-padawan** [comment]
I have just submitted #29 for focused state, so let me update this one to cover `disabled`.

**Comment by web-padawan** [comment]
Actually, custom-field does not track `disabled` state on the wrapped components.

Having a `disabled` property propagating to all the wrapped components sounds like a new feature.
That would be aligned with how `<fieldset>` works (even though it's not the same purpose).

**Comment by Haprog** [comment]
When implementing this (for `disabled`), consider also implementing propagation of `readonly` attribute to wrapped components in a similar way (even if we don't have any styles for `readonly` affecting custom field itself). Not sure if we should open a separate issue about this, or edit this issue description to cover both?

**Comment by web-padawan** [comment]
@Haprog updated the issue title to use both `disabled` and `readonly`. 
I think it would be nice to have them both implemented at once.

**Comment by heruan** [comment]
@Haprog @web-padawan Any update on this?

**Comment by heruan** [comment]
Another issue: when the field is `required`, the label shows the blue dot even if the field is disabled. In `vaadin-text-field` instead a `required` but `disabled` field does not display the dot.

**Comment by Haprog** [comment]
@heruan unfortunately this issue is not on our priority list atm. so it is unlikely to be fixed soon unless we get a good quality external PR for fixing it.

Note that this issue should be only about fixing the label styles so the label and required indicator are styled in the same way as with out other field components (depending on "required", "disabled" and "readonly" state attributes). I think these attributes do not need to be automatically propagated to inner inputs by custom-field, since if the developer binds a value to these attributes for custom-field, they might just as easily bind the same value to any child fields that they want.

**Comment by Haprog** [comment]
I checked that in current stable version of vaadin-custom-field the focus styles of the label and focusing by clicking the label already seems to work as expected (same way as with vaadin-text-field) so the only thing missing for this issue is the disabled styles (and minor issue with readonly hover styles) for the label.

**Comment by Haprog** [comment]
This has now been fixed and the fix is included in the latest release `vaadin-custom-field` [v1.0.11](https://github.com/vaadin/vaadin-custom-field/releases/tag/v1.0.11).
